name: Stast

on: 
 # push:
  #  branches: [ main ]
  schedule: 
    - cron: '0 0 * * *'
jobs: 
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write


    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          
      - name: Run script
        run: python .hello-git-curso/stats.py # .Ruta
        
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Optional. Commit message for the created commit.
          commit_message: Update stats
          commit_user_name: Cesir72 [GitHub Actions] # defaults to "github-actions[bot]"
          commit_user_email: chechare71@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: César SM 
